const config = {
	github: {
		username: 'imnavanath',
		sortBy: 'stars',
		limit: 10,
		exclude: {
			forks: false,
			projects: [''],
		},
	},
	social: {
		linkedin: 'navanath-bhosale',
		paypal: 'NavanathBhosale',
		facebook: '',
		instagram: 'i_am_navanath',
		wordpress: 'navanathbhosale',
		dev: 'imnavanath',
		website: 'https://imnavanath.github.io/meet-me/',
		phone: '+918177877802',
		email: 'navanath.bhosale95@gmail.com',
	},
	skills: [
		'PHP',
		'CSS',
		'JavaScript',
		'jQuery',
		'React.js',
		'MySQL',
		'Git',
		'Tailwind',
		'Bootstrap',
		'WordPress',
	],
	experiences: [
		{
			company: 'Brainstorm Force',
			position: 'Senior Software Developer',
			from: 'February 2018',
			to: 'Present',
		}
	],
    education: [
		{
			institution: 'Envision Institute, Nigadi',
			degree: 'Semantic Web Design-Development',
			from: '2017',
			to: '2018',
		},
		{
			institution: 'Pimpri Chinchwad College of Engineering',
			degree: 'Bachelor of Computer Science',
			from: '2013',
			to: '2017',
		},
		{
			institution: 'K.N.M.G Jr College, Chinchwad',
			degree: 'Higher Secondary Certificate (HSC)',
			from: '2010',
			to: '2012',
		},
		{
			institution: 'Smt. S. D. Gange Prashala',
			degree: 'Secondary School Certificate (SSC)',
			from: '2000',
			to: '2010',
		},
	],
	blog: {
		source: 'dev',
		username: 'imnavanath',
		limit: 3,
	},
	googleAnalytics: {
		// GA3 tracking id UA-XXXXXXXXX-X | G-XXXXXXXXXX
		id: '',
	},
	themeConfig: {
		defaultTheme: 'corporate',
		disableSwitch: false,
		respectPrefersColorScheme: false,
		themes: [
			'light',
			'dark',
			'cupcake',
			'bumblebee',
			'emerald',
			'corporate',
			'synthwave',
			'retro',
			'cyberpunk',
			'valentine',
			'halloween',
			'garden',
			'forest',
			'aqua',
			'lofi',
			'pastel',
			'fantasy',
			'wireframe',
			'black',
			'luxury',
			'dracula',
			'cmyk',
			'autumn',
			'business',
			'acid',
			'lemonade',
			'night',
			'coffee',
			'winter',
			'procyon',
		],
		customTheme: {
			primary: '#fc055b',
			secondary: '#219aaf',
			accent: '#e8d03a',
			neutral: '#2A2730',
			'base-100': '#E3E3ED',
			'--rounded-box': '3rem',
			'--rounded-btn': '3rem',
		},
	},
};

export default config;
